In [1]:
import numpy as np

# Crear arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print("Array a:", a)
print("Array b:", b)
print("Suma:", a + b)
print("Multiplicación:", a * b)
print("Forma:", a.shape)
print("Tipo de dato:", a.dtype)

Array a: [1 2 3 4 5]
Array b: [10 20 30 40 50]
Suma: [11 22 33 44 55]
Multiplicación: [ 10  40  90 160 250]
Forma: (5,)
Tipo de dato: int64


In [2]:
# Array 2D (matriz)
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Matriz:\n", matriz)
print("Forma:", matriz.shape)       # filas x columnas
print("Elemento [0,0]:", matriz[0, 0])  # primera fila, primera columna
print("Elemento [1,2]:", matriz[1, 2])  # segunda fila, tercera columna
print("Primera fila:", matriz[0, :])
print("Segunda columna:", matriz[:, 1])

Matriz:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Forma: (3, 3)
Elemento [0,0]: 1
Elemento [1,2]: 6
Primera fila: [1 2 3]
Segunda columna: [2 5 8]


In [3]:
# Operaciones estadísticas
print("Suma total:", matriz.sum())
print("Promedio:", matriz.mean())
print("Valor máximo:", matriz.max())
print("Valor mínimo:", matriz.min())

# Reshape: cambiar la forma sin cambiar los datos
vector = np.array([1, 2, 3, 4, 5, 6])
matriz_2x3 = vector.reshape(2, 3)
print("\nVector original:", vector)
print("Convertido a 2x3:\n", matriz_2x3)

Suma total: 45
Promedio: 5.0
Valor máximo: 9
Valor mínimo: 1

Vector original: [1 2 3 4 5 6]
Convertido a 2x3:
 [[1 2 3]
 [4 5 6]]


In [4]:
import pandas as pd

# Crear un DataFrame (tabla de datos)
datos = {
    "nombre": ["Ana", "Luis", "María", "Carlos"],
    "edad":   [23, 35, 28, 41],
    "ciudad": ["Madrid", "Lima", "Bogotá", "Madrid"],
    "salario": [3000, 4500, 3800, 5200]
}

df = pd.DataFrame(datos)
print(df)

   nombre  edad  ciudad  salario
0     Ana    23  Madrid     3000
1    Luis    35    Lima     4500
2   María    28  Bogotá     3800
3  Carlos    41  Madrid     5200


In [5]:
# Explorar el DataFrame
print("Forma:", df.shape)           # cuántas filas y columnas
print("\nPrimeras filas:\n", df.head(2))
print("\nResumen estadístico:\n", df.describe())
print("\nFiltrar mayores de 30:\n", df[df["edad"] > 30])
print("\nOrdenar por salario:\n", df.sort_values("salario", ascending=False))

Forma: (4, 4)

Primeras filas:
   nombre  edad  ciudad  salario
0    Ana    23  Madrid     3000
1   Luis    35    Lima     4500

Resumen estadístico:
             edad      salario
count   4.000000     4.000000
mean   31.750000  4125.000000
std     7.889867   942.956344
min    23.000000  3000.000000
25%    26.750000  3600.000000
50%    31.500000  4150.000000
75%    36.500000  4675.000000
max    41.000000  5200.000000

Filtrar mayores de 30:
    nombre  edad  ciudad  salario
1    Luis    35    Lima     4500
3  Carlos    41  Madrid     5200

Ordenar por salario:
    nombre  edad  ciudad  salario
3  Carlos    41  Madrid     5200
1    Luis    35    Lima     4500
2   María    28  Bogotá     3800
0     Ana    23  Madrid     3000
