# US-03: Introducción a tensores en PyTorch

Los tensores son la estructura de datos fundamental en PyTorch — equivalen a los arrays de NumPy pero con soporte para GPU y cálculo automático de gradientes.

## 1. Crear tensores

In [2]:
import torch

# Crear tensores de distintas formas
t1 = torch.tensor([1, 2, 3, 4, 5])
t2 = torch.zeros(3, 3)
t3 = torch.ones(2, 4)
t4 = torch.rand(3, 3)

print("Desde lista:", t1)
print("\nCeros:\n", t2)
print("\nUnos:\n", t3)
print("\nAleatorio:\n", t4)

Desde lista: tensor([1, 2, 3, 4, 5])

Ceros:
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Unos:
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Aleatorio:
 tensor([[0.5161, 0.8262, 0.2421],
        [0.4455, 0.1026, 0.1287],
        [0.0638, 0.2087, 0.9744]])


## 2. Conversión NumPy ↔ PyTorch

In [3]:
# Crear tensores desde NumPy y viceversa
import numpy as np

array_np = np.array([1.0, 2.0, 3.0])
tensor_desde_np = torch.from_numpy(array_np)
de_vuelta_a_np = tensor_desde_np.numpy()

print("NumPy array:", array_np)
print("Tensor desde NumPy:", tensor_desde_np)
print("De vuelta a NumPy:", de_vuelta_a_np)

# dtype y shape
print("\nTipo de dato:", tensor_desde_np.dtype)
print("Forma:", tensor_desde_np.shape)
print("Dispositivo:", tensor_desde_np.device)

NumPy array: [1. 2. 3.]
Tensor desde NumPy: tensor([1., 2., 3.], dtype=torch.float64)
De vuelta a NumPy: [1. 2. 3.]

Tipo de dato: torch.float64
Forma: torch.Size([3])
Dispositivo: cpu


## 3. Operaciones aritméticas y reshape

In [4]:
# Operaciones aritméticas y reshape
a = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
b = torch.tensor([[5.0, 6.0], [7.0, 8.0]])

print("Suma:\n", a + b)
print("\nMultiplicación elemento a elemento:\n", a * b)
print("\nMultiplicación matricial:\n", torch.matmul(a, b))

# Reshape
tensor = torch.arange(1, 13)  # números del 1 al 12
print("\nVector:", tensor)
print("Reshape a 3x4:\n", tensor.reshape(3, 4))
print("Reshape a 2x6:\n", tensor.reshape(2, 6))

Suma:
 tensor([[ 6.,  8.],
        [10., 12.]])

Multiplicación elemento a elemento:
 tensor([[ 5., 12.],
        [21., 32.]])

Multiplicación matricial:
 tensor([[19., 22.],
        [43., 50.]])

Vector: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
Reshape a 3x4:
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
Reshape a 2x6:
 tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])


## 4. Autograd — cálculo automático de gradientes

In [5]:
# requires_grad: el corazón del entrenamiento
x = torch.tensor([2.0], requires_grad=True)

# Operación: y = x² + 3x
y = x**2 + 3*x

print("x:", x)
print("y:", y)

# Calcular gradiente (derivada de y respecto a x)
y.backward()
print("Gradiente dy/dx:", x.grad)  # debería ser 2x + 3 = 7

x: tensor([2.], requires_grad=True)
y: tensor([10.], grad_fn=<AddBackward0>)
Gradiente dy/dx: tensor([7.])


## 5. Ejercicio final — operación matricial completa

In [6]:
# Ejercicio final: operaciones matriciales solo con PyTorch

# Matriz de datos simulada (5 muestras, 3 características)
X = torch.rand(5, 3)

# Pesos simulados (3 características → 1 salida)
W = torch.rand(3, 1)

# Bias
b = torch.zeros(1)

# Predicción: y = X @ W + b
y = torch.matmul(X, W) + b

print("Datos X (5x3):\n", X.round(decimals=2))
print("\nPesos W (3x1):\n", W.round(decimals=2))
print("\nPredicciones y (5x1):\n", y.round(decimals=2))
print("\nForma de y:", y.shape)

Datos X (5x3):
 tensor([[0.2600, 0.8900, 0.7900],
        [0.5200, 0.5000, 0.0800],
        [0.7000, 0.1500, 0.8800],
        [0.0100, 0.9600, 0.5000],
        [0.1300, 0.3300, 0.0800]])

Pesos W (3x1):
 tensor([[0.2600],
        [0.4400],
        [0.9700]])

Predicciones y (5x1):
 tensor([[1.2300],
        [0.4300],
        [1.1000],
        [0.9100],
        [0.2600]])

Forma de y: torch.Size([5, 1])


## Glosario

| Término | Definición |
|---|---|
| **Tensor** | Estructura de datos fundamental en PyTorch. Equivale a un array de NumPy pero con soporte para GPU y cálculo automático de gradientes. |
| **dtype** | Tipo de dato del tensor (int64, float32, float64). En redes neuronales se usa casi siempre float32. |
| **shape** | Forma del tensor — indica cuántas dimensiones tiene y cuántos elementos hay en cada una. Ej: (5, 3) = 5 filas, 3 columnas. |
| **device** | Indica dónde vive el tensor: cpu o cuda (GPU). |
| **reshape** | Cambia la forma del tensor sin modificar sus datos. Ej: un vector de 12 elementos puede reorganizarse como matriz 3x4. |
| **Multiplicación elemento a elemento** | Multiplica cada elemento con su correspondiente. Se hace con `*`. |
| **Multiplicación matricial** | Operación matemática entre matrices. Se hace con `torch.matmul()`. Es la operación principal dentro de una red neuronal. |
| **Peso (W)** | Número que indica qué tan importante es cada característica para la predicción. El modelo los aprende durante el entrenamiento. |
| **Bias (b)** | Valor base de ajuste independiente de los datos. Le da más flexibilidad al modelo. |
| **requires_grad** | Le indica a PyTorch que registre las operaciones sobre ese tensor para poder calcular gradientes. |
| **Gradiente** | Derivada de la función de pérdida respecto a un parámetro. Indica cuánto y en qué dirección ajustar los pesos. |
| **autograd** | Motor de PyTorch que calcula gradientes automáticamente. Se activa con `.backward()`. |
| **Autograd / backward()** | Calcula automáticamente todos los gradientes de una operación. Es lo que hace posible entrenar redes neuronales sin calcular derivadas a mano. |